[package]
name = "withgdnative"
version = "0.1.0"
authors = ["Christian Mauduit (ufoot) <ufoot@ufoot.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdnative = "0.9.1"
purelib = { path = "../purelib" }