#!/bin/sh

if [ "$2" = "macosx" ]; then
   echo "<macosx-sdk-path>/MacOSX<macosx-sdk-version>.sdk"
elif [ "$2" = "iphoneos" ]; then
   echo "<ios-sdk-path>/iPhoneOS<ios-sdk-version>.sdk"
else
   echo ""
fi
