#!/bin/sh

if [ "$3" = "macosx" ]; then
   echo "<macosx-sdk-path>/MacOSX<macosx-sdk-version>.sdk"
elif [ "$3" = "iphoneos" ]; then
   echo "<ios-sdk-path>/iPhoneOS<ios-sdk-version>.sdk"
else
   echo "this-should-not-happen $1 $2 $3"
fi
